name: Continuous Integration

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_PATH: 'AnonWallClient.csproj'

jobs:
  test-build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        framework: 
          - net8.0-android
          - net8.0-windows10.0.19041.0
          - net8.0-ios
          - net8.0-maccatalyst
        exclude:
          # Windows can't build iOS/macOS
          - os: windows-latest
            framework: net8.0-ios
          - os: windows-latest
            framework: net8.0-maccatalyst
          # macOS can't build Windows
          - os: macos-latest
            framework: net8.0-windows10.0.19041.0

    runs-on: ${{ matrix.os }}
    name: Test Build (${{ matrix.framework }} on ${{ matrix.os }})
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Setup Java JDK (Android only)
        if: matrix.framework == 'net8.0-android'
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '11'

      - name: Install MAUI workload
        run: dotnet workload install maui --skip-sign-check

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.PROJECT_PATH }} -c Debug -f ${{ matrix.framework }} --no-restore

  code-quality:
    runs-on: windows-latest
    name: Code Quality Check
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI workload
        run: dotnet workload install maui --skip-sign-check

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Check code formatting (informational)
        run: dotnet format --verbosity diagnostic
        continue-on-error: true

      - name: Run static analysis
        run: dotnet build ${{ env.PROJECT_PATH }} -c Debug -f net8.0-windows10.0.19041.0 --verbosity normal

  security-scan:
    runs-on: windows-latest
    name: Security Vulnerability Scan
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI workload
        run: dotnet workload install maui --skip-sign-check

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: Check for vulnerable packages
        run: |
          echo "Checking for security vulnerabilities..."
          $result = dotnet list ${{ env.PROJECT_PATH }} package --vulnerable --include-transitive 2>&1
          if ($LASTEXITCODE -eq 0) {
            Write-Host "? No known vulnerabilities found in packages"
          } else {
            Write-Host "?? Potential vulnerabilities detected:"
            Write-Host $result
            exit 1
          }
        shell: pwsh

  dependency-check:
    runs-on: windows-latest
    name: Dependency Analysis
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Install MAUI workload
        run: dotnet workload install maui --skip-sign-check

      - name: Restore dependencies
        run: dotnet restore ${{ env.PROJECT_PATH }}

      - name: List all packages
        run: dotnet list ${{ env.PROJECT_PATH }} package --include-transitive

      - name: Check for outdated packages
        run: |
          echo "Checking for outdated packages..."
          dotnet list ${{ env.PROJECT_PATH }} package --outdated || echo "No outdated packages or tool not available"
        continue-on-error: true